### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by gackelchen** [balinbob/yrc#2]
After doing the installation (install.md)
and entering:

> ./libgyrc/gyrc.py

I got:

> Traceback (most recent call last):
>   File "./libgyrc/gyrc.py", line 7, in <module>
>     from .ifrunning import listen_for_activation, activate_if_already_running
> ImportError: attempted relative import with no known parent package
> 
Thanx for help!

**Comment by balinbob** [comment]
Run ./gyrc instead of ./libgyrc/gyrc.py

Thank You!
