### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by steppi-bersche** [balinbob/yrc#3]
Hi Bob,
great app! I am so thankful that you started the programming of the AV Control on Linux.

I followed the procedure for the installation according your install file. Everything (like Py installations, etc.) went well until I started 

./libgyrc/gyrc.py

I installed the YRC in the folder ~/git/yrc

But that unfortunately results in an error:

> Traceback (most recent call last):
>   File "./libgyrc/gyrc.py", line 7, in <module>
>     from .ifrunning import listen_for_activation, activate_if_already_running
> ImportError: attempted relative import with no known parent package
> 

I am using Linuxmint 20.

Grateful for any hint to resolve it :-).

Thanks a lot and all the best
steppi

**Comment by balinbob** [comment]
Hi Steppi,
Instead of running this:  ./libgyrc/gyrc.py
Run this:    ./gyrc.py
(It is in the same folder as the libgyrc folder)

You may run into other problems with it; I hope to resume work on it some day.   It works great for me, however.

**Comment by balinbob** [comment]
Excuse me!   It is ./gyrc not ./gyrc.py .

Bob

**Comment by Radiatorx** [comment]
Hi Bob,
agree this looks really interesting!
I got about the same problem as Steppi, resolved that, was able to submit my Musiccast equipment IP address - looked it up in the config file, it's there - but when executing the Gyrc file it only starts the receiver. No GUI, nothing more. Guess this starting is as the Gyrc contacts the receiver and then it wakes up. Further execution leads to nothing. 
Anything else I should do or should happen? 
I am using Linux MX a Debian derivative without SystemD (which sometimes has consequences). 

All guidance appreciated as it would be ever so interesting to get this running on my Linux.

BR

**Comment by balinbob** [comment]
@Radiatorx , Thank you for your report!    Let's start with a couple of things:

1.  Are you running Gyrc in a terminal?   If not, please do so, so you can see the debug output and post it here.
2. What Desktop Environment are you running, and have you checked to see whether you have the GTK+ 3 python modules installed to support the GUI?
Here is at least a partial list (I'm on Debian 10 right now):

+ python3-dbus
+ python3-gi          (python 3 gobject-introspection)
or on Ubuntu:  python3-pygobject

You also need to be sure the icons are getting installed, they are .png files in ~/.gyrc/icons/*.png

Bob

**Comment by Radiatorx** [comment]
Bob,

Many thanks for the fast reply. 

Response to your comments with the same numbering

1. Looks like this when running from terminal
$ ./gyrc

(gyrc:29982): Gtk-WARNING **: 16:13:33.168: Locale not supported by C library.
        Using the fallback 'C' locale.

(gyrc:29982): Gtk-WARNING **: 16:13:33.181: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(gyrc:29982): Gtk-WARNING **: 16:13:33.181: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(gyrc:29982): Gtk-WARNING **: 16:13:33.181: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(gyrc:29982): Gtk-WARNING **: 16:13:33.190: Theme parsing error: gtk.css:3691:13: Not using units is deprecated. Assuming 'px'.
Icons installed? 
srcpath is  /home/Peter/Yamma/yrc/icons
True
trying port 5010
Got It!
connected to bibblan
max volume for this device is:  80
gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/tmp/cover.jpg” (3)
Traceback (most recent call last):
  File "./gyrc", line 11, in <module>
    sys.exit(main())
  File "/home/Peter/Yamma/yrc/libgyrc/gyrc.py", line 230, in main
    win = YamaWin()
  File "/home/Peter/Yamma/yrc/libgyrc/gyrc.py", line 130, in __init__
    self.volSlider.set_value(self.mcd.get_volume_db())
  File "/home/Peter/Yamma/yrc/libgyrc/mcd.py", line 125, in get_volume_db
    return status.get('actual_volume').get('value')
AttributeError: 'NoneType' object has no attribute 'get'
 
So something is not working like it should with GTK. possibly other issues as well. 

2.  Desktop Environment = KDE PLasma
not sure how I check python GTK+ 3 modules are there but I have installed 
- python3-dbus
- python3-gi

3. Icons are in ~/.gyrc/icons/*.png

Again, any assistance is much appreciated!

Best
Peter

**Comment by balinbob** [comment]
Which receiver model do you have?   I only have an RX-V485, and a pair of wx-021 speakers.

return status.get('actual_volume').get('value')
AttributeError: 'NoneType' object has no attribute 'get'

This is not a problem with GTK, it has to do with what information pymusiccast is receiving from your receiver.
My receiver gets the 'actual_volume' attribute, but the speakers do not.   I may have to update my code for your receiver.  (You do have to enter the receiver first in the ip address setup, btw.)

I will continue investigating.   Thanks.

**Comment by Radiatorx** [comment]
Hi,
Receiver  is R-N402D. As far as I understand it [should] use the same protocol etc as all other receivers ... but ok, there is probably a difference between a stereo (mine) and an AV (yours). Speakers could have some other variation, I really thought it was the very same base protocol. Oh well. 

Have entered the receiver IP address, only have a receiver, no musiccast speakers. So for me, one option only. 

Many thanks for all efforts! 

Best  /P

**Comment by balinbob** [comment]
Would you please type the following into a python interpreter and send me back the output?
This way I can tell what your receiver is reporting.

type 'python3'

`from pymusiccast import McDevice`
`mcd = McDevice('your-recvr-ip-addr')`
`print(mcd.get_status())`

Thank you!

**Comment by Radiatorx** [comment]
Peter@Peter1-mx:~/Yamma/yrc
$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymusiccast import McDevice
>>> mcd = McDevice('your-recvr-ip-addr')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
....
>>> mcd = McDevice('your-recvr-ip-addr')
KeyboardInterrupt
>>> print(mcd.get_status())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mcd' is not defined

//P

**Comment by balinbob** [comment]
Thank you.   I should have said, replace 'your-recvr-ip-addr' with your actual ip address for your receiver.

**Comment by Radiatorx** [comment]
stupid of me! Did not look at the arguments, just copied.

OK, now it's better:

Peter@Peter1-mx:~/Yamma/yrc
$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymusiccast import McDevice
>>> mcd = McDevice('192.168.0.241')
>>> print(mcd.get_status())
{'response_code': 0, 'power': 'on', 'sleep': 0, 'volume': 25, 'mute': False, 'max_volume': 80, 'input': 'server', 'distribution_enable': True, 'tone_control': {'mode': 'manual', 'bass': 1, 'treble': 2}, 'balance': 1, 'link_control': 'standard', 'link_audio_quality': 'compressed', 'disable_flags': 0}
>>>


Note: don't think this will change much but I had a look on the set-up just using the ip-address in a browser. Noticed network was set to Extension(1) which I changed to Wired - rebooted the receiver. Some minutes after that I got a request to up-date firmware from 1.15 to 1.17 (which I took). Above you see the result after the update.

//Peter

**Comment by balinbob** [comment]
Thanks.   Your stereo receiver does not have 'volume_db' (although it may after the update).   It will take me a little time to use 'volume' instead of 'volume_db', but I think I can do it if you want to check back later.

Bob

**Comment by Radiatorx** [comment]
Interesting, guess volume in an AV must be calibrated which is not necessary in a stereo. Still the potentiometer are logarithmic, Yam could have used the same parameter for both. 
Interested I am!

Peter

**Comment by balinbob** [comment]
Peter, the experimental branch is not complete, but you should be able to use it if there are no other incompatibilities.
`git clone -b experimental https://github.com/balinbob/yrc`
Please let me know when you get the chance.

Bob

**Comment by Radiatorx** [comment]
Bob, it works!  Great!!

I am getting some few error messages, some shown below.
I can control the volume, can fast forward / backward. Nice - the android app can't do that!  (FF, FB)
also here some error messages, some shown below. 
Clearly, one can ignore these error messages, but you might want to know

Seems I can also select source. Mostly using Server - here you program stops at "Server"-level, if I want to actually select an audio file that has to be via the android app. 

Since last I got myself a (used) Yamaha WXAD-10 (similar to Chromecast) which also has musiccast. Your program connects very nicely to this one as well, I have not yet tried to control the WXAD with your program, this might be more tricky as it is a minimal node - the WXAD-10 has eg no volume control, neither physical nor to be controlled (or to make it more complicated, in one set-up it is possible to control the volume). 

All this very briefly, it is a bit late where I live and tomorrow is yet another working day. More testing tomorrow. 

Many thanks for this! It is really great to control also from my lap-top.
//Peter

Error messages at start:
(gyrc:8636): Gtk-WARNING **: 21:41:33.733: Locale not supported by C library.
        Using the fallback 'C' locale.

(gyrc:8636): Gtk-WARNING **: 21:41:33.747: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(8 in total)

when adjusting the volume I get
vol_up:  20.5
mcd.increase_vol
mcd.increase_vol
vol_up:  23.0
mcd.increase_vol
TypeError: can't convert return value to desired type
TypeError: can't convert return value to desired type
mcd.decrease_volume volume is  22

some other error messages
^CTraceback (most recent call last):
  File "./gyrc", line 11, in <module>
    sys.exit(main())
  File "/home/Peter/Yam22/yrc/libgyrc/gyrc.py", line 227, in main
    Gtk.main()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1630, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)

**Comment by balinbob** [comment]
Peter, most of that either has nothing to do with gyrc or are simply debug messages.   The TypeError is my error though, but it doesn't affect anything and I haven't figured out how to correct it.  You may want to look up how to set your locale for your distribution.   Yes, it doesn't go as far as browsing servers, that would be a huge project.

There is another minor update to the experimental branch.

Please feel free to open any other issues as you try it out, but please put them in new issues, so I can track them separately.
Bob
