### ISSUE TITLE
Error in launching app

### ISSUE THREAD

**Issue by chabchab** [balinbob/yrc#4]
Hello, thanks for sharing this app !
I installed it but I have this error :

[benoit@localhost yrc]$ ./gyrc 
Icons installed? 
srcpath is  /home/benoit/Personnel/music/yrc/icons
True
trying port 5010
Got It!
connected to Cuisine
max volume for this device is:  60
Traceback (most recent call last):
  File "./gyrc", line 11, in <module>
    sys.exit(main())
  File "/home/benoit/Personnel/music/yrc/libgyrc/gyrc.py", line 230, in main
    win = YamaWin()
  File "/home/benoit/Personnel/music/yrc/libgyrc/gyrc.py", line 130, in __init__
    self.volSlider.set_value(self.mcd.get_volume_db())
  File "/home/benoit/Personnel/music/yrc/libgyrc/mcd.py", line 125, in get_volume_db
    return status.get('actual_volume').get('value')
AttributeError: 'NoneType' object has no attribute 'get'

(for your documentation, in fedora the package " pygobject3 python3-gobject")
thanks in advance !

**Comment by chabchab** [comment]
More informtion about device : it is a Musiccast 20 with last firmware Version : 1.84

**Comment by balinbob** [comment]
Thank you!

Please try the experimental branch to see if it solves the problem.

Bob

**Comment by chabchab** [comment]
It works with experimental branch ! Thanks for your work,
And happy new year :)
