### ISSUE TITLE
ip address(es) not configured

### ISSUE THREAD

**Issue by Anthocyanina** [balinbob/yrc#5]
When trying the program for the first time, i went to ~/yrc and used ./gyrc and got a small window asking me to enter the ip adddress of the receiver. I entered the ip address and clicked on done, the window closed itself and nothing happened. Trying to run it again results in this output from the terminal and nothing else happens:

~/yrc$ ./gyrc
Icons installed? 
srcpath is  /home/sara/yrc/icons
True
ip address(es) not configured
~/yrc$

Any idea how to fix this? deleting the yrc folder and copying it again doesn't do anything. form the gyrc file i don't understand what it's doing so i don't know if it's storing settings anywhere to remove them. the only mention of "ip_address" in the gyrc.py file is set equal to None but changing that does nothing. Thank you.

**Comment by balinbob** [comment]
Hello, I am eager to help you with this problem, right now I am travelling
and must return to my home.

Are you certain you are entering the correct IP address for the receiver,
and what model is it, please?

Bob

**Comment by Anthocyanina** [comment]
Hi! thank you for the reply, and of course, there's no rush, thank you. The model is the RX V4A. I was only able to enter the ip address once as the window to enter it never showed up again, so I'm not completely sure it was the right address and see no way to modify it or do anything else.

**Comment by balinbob** [comment]
Hello, I imagine your receiver is compatible, I have two thoughts on what
the problem might be.   The best thing might be to cat .gyrc/gyrc.cfg

and see if it has the ip address of your receiver (correctly)
If it does not, please create that file and enter only the ip address for
your receiver.   This is in your home folder.

Please let me know when you get a chance.   Thank you.

Bob

**Comment by Anthocyanina** [comment]
> 

Thanks! this solved the problem. The file existed but was empty, adding the ip address then typing ./gyrc in ~/yrc$ now properly shows the controls, thanks again!
